---
title: "data"
output: html_notebook
---

This is where the final project report write-up goes. 
```{r}
library(tidytuesdayR)
library(tidyverse)
```

Get the data
```{r}
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

# tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv')
# 
# historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
```

Rename column from state_name to state so we can join easily
```{r}
colnames(salary_potential)[3] <- "state"
```

Join `tuition_cost`, `diversity_school`, and `salary_potential`
```{r}
college_data <- dplyr::left_join(tuition_cost, diversity_school, by = c("name", "state"))
college_data <- dplyr::left_join(college_data, salary_potential, by = c("state", "name"))
```

Pivot tables to change race variable from row to column
```{r}
college_data <- college_data %>% 
  pivot_wider(names_from=category, values_from=enrollment) %>% 
  select(-"NA")
```

Data wrangling
```{r}
college_data <- college_data %>%
  rename(asian=Asian, women=Women, 
         native_american="American Indian / Alaska Native", 
         black=Black, hispanic=Hispanic, 
         pacific_islander="Native Hawaiian / Pacific Islander", 
         white=White, two_more_races="Two Or More Races", 
         unkown=Unknown,
         foreign="Non-Resident Foreign", 
         total_minority="Total Minority")
```

```{r}
glimpse(college_data)
```


Export `college_data` as csv file
```{r}
write.csv(college_data, "./college_data.csv", row.names = F)
```



